sylius_resource:
    resources:
        webburza_location.location:
            classes:
                repository: Webburza\Sylius\LocationBundle\Doctrine\ORM\LocationRepository
                model: Webburza\Sylius\LocationBundle\Entity\Location
                form: Webburza\Sylius\LocationBundle\Form\Type\LocationType
            translation:
                classes:
                    model: Webburza\Sylius\LocationBundle\Entity\LocationTranslation
                    form: Webburza\Sylius\LocationBundle\Form\Type\LocationTranslationType

        webburza_location.location_type:
            classes:
                model: Webburza\Sylius\LocationBundle\Entity\LocationType
                form: Webburza\Sylius\LocationBundle\Form\Type\LocationTypeType
            translation:
                classes:
                    model: Webburza\Sylius\LocationBundle\Entity\LocationTypeTranslation
                    form: Webburza\Sylius\LocationBundle\Form\Type\LocationTypeTranslationType

        webburza_location.location_image:
            classes:
                model: Webburza\Sylius\LocationBundle\Entity\LocationImage
                form: Webburza\Sylius\LocationBundle\Form\Type\LocationImageType

liip_imagine:
    filter_sets:
        sylius_255x255:
            filters:
                thumbnail: { size: [255, 255] }

webburza_sylius_location:
    google_maps_enabled: false
    google_maps_key: 1234567890
