imports:
    - { resource: grids/location.yml }
    - { resource: grids/location_type.yml }

sylius_resource:
    resources:
        webburza_location.location:
            classes:
                repository: Webburza\Sylius\LocationBundle\Doctrine\ORM\LocationRepository
                model: Webburza\Sylius\LocationBundle\Entity\Location
                form:
                    default: Webburza\Sylius\LocationBundle\Form\Type\LocationType
            translation:
                classes:
                    model: Webburza\Sylius\LocationBundle\Entity\LocationTranslation
                    form:
                        default: Webburza\Sylius\LocationBundle\Form\Type\LocationTranslationType

        webburza_location.location_type:
            classes:
                repository: Webburza\Sylius\LocationBundle\Doctrine\ORM\LocationTypeRepository
                model: Webburza\Sylius\LocationBundle\Entity\LocationType
                form:
                    default: Webburza\Sylius\LocationBundle\Form\Type\LocationTypeType
            translation:
                classes:
                    model: Webburza\Sylius\LocationBundle\Entity\LocationTypeTranslation
                    form:
                        default: Webburza\Sylius\LocationBundle\Form\Type\LocationTypeTranslationType

        webburza_location.location_image:
            classes:
                model: Webburza\Sylius\LocationBundle\Entity\LocationImage
                form:
                    default: Webburza\Sylius\LocationBundle\Form\Type\LocationImageType

liip_imagine:
    filter_sets:
        sylius_255x255:
            filters:
                thumbnail: { size: [255, 255] }

doctrine:
    orm:
        resolve_target_entities:
            Webburza\Sylius\LocationBundle\Entity\LocationInterface: %webburza_location.model.location.class%

#assetic:
#    bundles:        ['WebburzaSyliusLocationBundle']
