imports:
    - { resource: parameters.yml }
    - { resource: grids/location.yml }
    - { resource: grids/location_type.yml }

doctrine:
    orm:
        resolve_target_entities:
            Webburza\Sylius\LocationBundle\Model\LocationImageInterface: '%webburza_location.model.location_image.class%'
            Webburza\Sylius\LocationBundle\Model\LocationTypeInterface: '%webburza_location.model.location_type.class%'
            Webburza\Sylius\LocationBundle\Model\LocationInterface: '%webburza_location.model.location.class%'
        entity_managers:
            default:
                mappings:
                    WebburzaSyliusLocationBundle:
                        type: xml
                        prefix: Webburza\Sylius\LocationBundle\Model
                        dir: 'Resources/config/doctrine'
                        is_bundle: true
                        mapping: true

sylius_resource:
    resources:
        webburza_location.location:
            classes:
                repository: '%webburza_location.repository.location.class%'
                model: '%webburza_location.model.location.class%'
                form: '%webburza_location.form.type.location.class%'
            translation:
                classes:
                    model: '%webburza_location.model.location_translation.class%'
                    form: '%webburza_location.form.type.location_translation.class%'

        webburza_location.location_type:
            classes:
                model: '%webburza_location.model.location_type.class%'
                form: '%webburza_location.form.type.location_type.class%'
            translation:
                classes:
                    model: '%webburza_location.model.location_type_translation.class%'
                    form: '%webburza_location.form.type.location_translation.class%'

        webburza_location.location_image:
            classes:
                model: '%webburza_location.model.location_image.class%'
                form: '%webburza_location.form.type.location_image.class%'

liip_imagine:
    filter_sets:
        sylius_260x260:
            filters:
                thumbnail: { size: [260, 260] }

webburza_sylius_location:
    google_maps_enabled: false
    google_maps_key: 1234567890
