sylius_resource:
    resources:
        webburza_location.location:
            classes:
                controller: Webburza\Sylius\LocationBundle\Controller\Backend\LocationController
                repository: Webburza\Sylius\LocationBundle\Doctrine\ORM\LocationRepository
                model: Webburza\Sylius\LocationBundle\Entity\Location
                form:
                    default: Webburza\Sylius\LocationBundle\Form\Type\LocationType
            translation:
                classes:
                    model: Webburza\Sylius\LocationBundle\Entity\LocationTranslation
                    form:
                        default: Webburza\Sylius\LocationBundle\Form\Type\LocationTranslationType

        webburza_location.location_type:
            classes:
                controller: Webburza\Sylius\LocationBundle\Controller\Backend\LocationTypeController
                model: Webburza\Sylius\LocationBundle\Entity\LocationType
                form:
                    default: Webburza\Sylius\LocationBundle\Form\Type\LocationTypeType
            translation:
                classes:
                    model: Webburza\Sylius\LocationBundle\Entity\LocationTypeTranslation
                    form:
                        default: Webburza\Sylius\LocationBundle\Form\Type\LocationTypeTranslationType

        webburza_location.location_image:
            classes:
                model: Webburza\Sylius\LocationBundle\Entity\LocationImage
                controller: Webburza\Sylius\LocationBundle\Controller\Backend\LocationImageController
                form:
                    default: Webburza\Sylius\LocationBundle\Form\Type\LocationImageType

liip_imagine:
    filter_sets:
        sylius_255x255:
            filters:
                thumbnail: { size: [255, 255] }

assetic:
    bundles:        ['WebburzaSyliusLocationBundle']

webburza_sylius_location:
    google_maps_key: 'AIzaSyAuLK2q9XfxEFcsu_FQSwY_S0WDM_k_z0Y'
    google_maps_enabled: true
