# ------------------------------------------------------------------------------
#  BACKEND
# ------------------------------------------------------------------------------

webburza_location_type:
    resource: |
        alias: webburza_location.location_type
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: webburza_location_type
        vars:
            all:
                subheader: sylius.ui.locationType
                templates:
                    form:   WebburzaSyliusLocationBundle:LocationType:_form.html.twig
            index:
                icon: archive
    type: sylius.resource
    prefix: /admin

webburza_location:
    resource: |
        alias: webburza_location.location
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: webburza_location
        vars:
            all:
                subheader: sylius.ui.location
                templates:
                    form:   WebburzaSyliusLocationBundle:Location:_form.html.twig
            index:
                icon: archive
    type: sylius.resource
    prefix: /admin

webburza_location_location_image_delete:
    path: /admin/location-image/{id}
    methods: [DELETE]
    defaults:
        _controller: webburza_location.controller.location_image:deleteAction
        _sylius:
            redirect:
                route: webburza_location_location_show
                parameters: { id: $locationId }
