# ------------------------------------------------------------------------------
#  BACKEND
# ------------------------------------------------------------------------------

webburza_location:
    resource: |
        section: admin
        alias: webburza_location.location
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: webburza_location
        vars:
            all:
                icon: marker
                templates:
                    form: WebburzaSyliusLocationBundle:Backend/Location:_form.html.twig
    type: sylius.resource
    prefix: /admin

webburza_location_type:
    resource: |
        section: admin
        alias: webburza_location.location_type
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: webburza_location_type
        vars:
            all:
                icon: sitemap
                templates:
                    form: WebburzaSyliusLocationBundle:Backend/LocationType:_form.html.twig
    type: sylius.resource
    prefix: /admin
