# ------------------------------------------------------------------------------
#  FRONTEND
# ------------------------------------------------------------------------------

webburza_location_frontend_index:
    path: /
    methods: [GET]
    defaults:
        _controller: WebburzaSyliusLocationBundle:Frontend\Location:index

webburza_location_frontend_show:
    path: /{slug}/
    methods: [GET]
    defaults:
        _controller: WebburzaSyliusLocationBundle:Frontend\Location:show
