# ------------------------------------------------------------------------------
#  BACKEND
# ------------------------------------------------------------------------------

webburza_location:
    resource: |
        alias: webburza_location.location
        templates: SyliusAdminBundle:Crud
        grid: webburza_location_location
        except: ['show']
        redirect: update
        vars:
            all:
                templates:
                    form: WebburzaSyliusLocationBundle:Backend/Location:_form.html.twig
    type: sylius.resource
    prefix: /admin

webburza_location_type:
    resource: |
        alias: webburza_location.location_type
        templates: SyliusAdminBundle:Crud
        grid: webburza_location_location_type
        except: ['show']
        redirect: update
        vars:
            all:
                templates:
                    form: WebburzaSyliusLocationBundle:Backend/LocationType:_form.html.twig
    type: sylius.resource
    prefix: /admin

webburza_location_location_image_delete:
    path: /admin/location-image/{id}
    methods: [DELETE]
    defaults:
        _controller: webburza_location.controller.location_image:deleteAction
        _sylius:
            redirect:
                route: webburza_location_location_show
                parameters: { id: $locationId }
