services:
    webburza_location.event_listener.admin_menu_builder:
        class: '%webburza_location.event_listener.admin_menu_builder.class%'
        arguments: ["@translator"]
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    webburza_location.event_listener.image_upload:
        class: '%webburza_location.event_listener.image_upload.class%'
        arguments:
            - '@sylius.image_uploader'
        tags:
            - { name: kernel.event_listener, event: webburza_location.location.pre_create, method: uploadLocationImage }
            - { name: kernel.event_listener, event: webburza_location.location.pre_update, method: uploadLocationImage }

    webburza_location.form.type.location:
        class: '%webburza_location.form.type.location.class%'
        arguments:
            - '%webburza_location.model.location.class%'
            - ['sylius']
            - '%webburza_location.model.location_type.class%'
        tags:
            - { name: form.type, alias: webburza_location_location }

    webburza_location.form.type.location_image:
        class: '%webburza_location.form.type.location_image.class%'
        arguments:
            - '%webburza_location.model.location_image.class%'
            - ['sylius']
        tags:
            - { name: form.type, alias: webburza_location_location_image }

    webburza_location.form.type.location_translation:
        class: '%webburza_location.form.type.location_translation.class%'
        arguments:
            - '%webburza_location.model.location_translation.class%'
            - ['sylius']
        tags:
            - { name: form.type, alias: webburza_location_location_translation }

    webburza_location.form.type.location_type:
        class: '%webburza_location.form.type.location_type.class%'
        arguments:
            - '%webburza_location.model.location_type.class%'
            - ['sylius']
        tags:
            - { name: form.type, alias: webburza_location_location_type }

    webburza_location.form.type.location_type_translation:
        class: '%webburza_location.form.type.location_type_translation.class%'
        arguments:
            - '%webburza_location.model.location_type_translation.class%'
            - ['sylius']
        tags:
            - { name: form.type, alias: webburza_location_location_type_translation }
