sylius_grid:
    grids:
        webburza_location:
            driver:
                name: doctrine/orm
                options:
                    class: '%webburza_location.model.location.class%'
            sorting:
                internalName: asc
            fields:
                internalName:
                    type: string
                    label: webburza_location.form.location.internal_name
                    sortable: ~
                locationType:
                    type: string
                    label: webburza_location.form.location.location_type
                    sortable: ~
                    path: locationType.name
                email:
                    type: string
                    label: webburza_location.form.location.email
                    sortable: ~
                latitude:
                    type: string
                    label: webburza_location.form.location.latitude
                    sortable: ~
                longitude:
                    type: string
                    label: webburza_location.form.location.longitude
                    sortable: ~
                phone:
                    type: string
                    label: webburza_location.form.location.phone
                    sortable: ~
                published:
                    type: twig
                    label: webburza_location.form.location.published
                    sortable: ~
                    options:
                        template: "SyliusUiBundle:Grid/Field:yesNo.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                    options:
                        format: Y-m-d H:i:s
            filters:
                internalName:
                    type: string
                    label: webburza_location.form.location.internal_name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
