sylius_grid:
    grids:
        webburza_location_type:
            driver:
                name: doctrine/orm
                options:
                    class: Webburza\Sylius\LocationBundle\Entity\LocationType
            sorting:
                id: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                updatedAt:
                    type: datetime
                    label: sylius.ui.updated_at
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete