sylius_grid:
    grids:
        webburza_location_type:
            driver:
                name: doctrine/orm
                options:
                    class: '%webburza_location.model.location_type.class%'
            sorting:
                id: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    options:
                        format: Y-m-d H:i:s
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
