sylius_grid:
    grids:
        webburza_location_location_type:
            driver:
                name: doctrine/orm
                options:
                    class: "%webburza_location.model.location_type.class%"
                    repository:
                        method: createListQueryBuilder
            filters:
                name:
                    type: string
                    label: webburza.sylius.location_type.label.name
                    options:
                        fields: [translation.name]
            fields:
                name:
                    type: string
                    label: webburza.sylius.location_type.label.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

